routes/web.php
<?php

use App\Http\Controllers\Admin\AdminController;
use App\Http\Controllers\Admin\ClientController;
use App\Http\Controllers\Admin\CompanyController;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Auth::routes(['register' => false,'reset' => false,'confirm' => false,'verify' => false]);
Route::middleware(['auth'])->group(function () {
    Route::get('/',[AdminController::class ,'index'])->name('home');
    Route::name('admin.')->prefix('admin')->group(function (){
        Route::resource('/companies', CompanyController::class)->names('companies');
        Route::resource('/clients', ClientController::class)->names('clients');
    });
});

app/Models/Client.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Client extends Model
{
    use HasFactory;

    const ROUTE_KEY = 'admin.clients';

    /**
     * The attributes that are mass assignable.
     *
     * @var string[]
     */
    protected $fillable = [
        'name',
        'surname',
        'email',
    ];

    /**
     * Relationship with companies
     *
     * @return \Illuminate\Database\Eloquent\Relations\HasMany
     */
    public function companies()
    {
        return $this->belongsToMany(Company::class);
    }

}

app/Http/Controllers/Admin/ClientController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use App\Http\Requests\ClientStoreRequest;
use App\Http\Requests\ClientUpdateRequest;
use App\Http\Requests\CompamyUpdateRequest;
use App\Models\Client;
use App\Models\Company;
use App\Services\ClientService;
use App\Services\CompanyService;
use Illuminate\Contracts\Foundation\Application;
use Illuminate\Contracts\View\Factory;
use Illuminate\Contracts\View\View;
use Illuminate\Http\RedirectResponse;
use Illuminate\Http\Request;
use Illuminate\Http\Response;

class ClientController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return Response
     */
    public function index(Request $request, ClientService $clientService)
    {
        if ($request->ajax()) {
            return $clientService->getClientsDatatable();
        }
        return view('admin.pages.clients.index');
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return Application|Factory|View
     */
    public function create(CompanyService $companyService)
    {
        $companies = $companyService->getCompaniesPluckIdName();
        return view('admin.pages.clients.create',compact('companies'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param ClientStoreRequest $request
     * @param ClientService $clientService
     * @return RedirectResponse
     */
    public function store(ClientStoreRequest $request, ClientService $clientService)
    {
        $clientService->create($request->validated());
        return redirect()->route('admin.clients.index')->with('success','Клієнта успішно створено');
    }

    /**
     * Display the specified resource.
     *
     * @param Client $client
     * @return Application|Factory|View
     */
    public function show(Client $client)
    {
        $client->load('companies:id,name');
        return view('admin.pages.clients.show',compact('client'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param Client $client
     * @param CompanyService $companyService
     * @return Application|Factory|View
     */
    public function edit(Client $client, CompanyService $companyService)
    {
        $companies = $companyService->getCompaniesPluckIdName();
        $client->load('companies:id,name');
        return view('admin.pages.clients.edit',compact('client','companies'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param ClientUpdateRequest $request
     * @param Client $client
     * @param ClientService $clientService
     * @return RedirectResponse
     */
    public function update(ClientUpdateRequest $request, Client $client, ClientService $clientService)
    {
        $clientService->update($client, $request->validated());
        return redirect()->route('admin.clients.index')->with('success','Дані клієнта успішно оновлено');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param Client $client
     * @return RedirectResponse
     */
    public function destroy(Client $client)
    {
        $client->delete();
        return redirect()->route('admin.clients.index')->with('success','Клієнта успішно видалено');
    }
}

resources/views/admin/pages/clients/create.blade.php
@extends('admin.layouts.app')
@section('content-page', 'Додати клієнта')
@section('content-title', 'Додати клієнта')
@section('content')

<div class="container-fluid col-lg-8 mt-2">
    <form method="POST" action="{{ route('admin.clients.store') }}">
        @csrf
        <div class="form-group col-lg-12 mb-2">
            <label for="inputName" class="col-xs-2 control-label">Ім'я:</label>
            <div class="col-xs-8">
                <input type="text" name="name" class="form-control" id="inputName" placeholder="Введіть ім'я"  value="{{old('name')}}">
                @error('name')
                <div class="alert alert-danger">{{ $message }}</div>
                @enderror
            </div>
        </div>
        <div class="form-group col-lg-12 mb-2">
            <label for="inputSurName" class="col-xs-2 control-label">Прізвище:</label>
            <div class="col-xs-8">
                <input type="text" name="surname" class="form-control" id="inputSurName" placeholder="Введіть прізвище"  value="{{old('surname')}}">
                @error('surname')
                <div class="alert alert-danger">{{ $message }}</div>
                @enderror
            </div>
        </div>
        <div class="form-group col-lg-12 mb-2">
            <label for="inputEmail" class="col-xs-2 control-label">Електрона адреса:</label>
            <div class="col-xs-8">
                <input type="text" name="email" class="form-control" id="inputEmail" placeholder="Введіть електронну адресу" value="{{old('email')}}">
                @error('email')
                <div class="alert alert-danger">{{ $message }}</div>
                @enderror
            </div>
        </div>
        <div class="form-group col-lg-12 mb-2">
            <label for="inputCompanies" class="col-xs-2 control-label">Компанії клієнта:</label>
            <div class="col-xs-8">
                <select name="companies[]" class="form-control select2" multiple="multiple" data-placeholder="Виберіть компанію закріплену за клієнтом">
                    @foreach($companies as $id => $name)
                        <option value="{{ $id }}">{{ $name }}</option>
                    @endforeach
                </select>
                @error('companies')
                <div class="alert alert-danger">{{ $message }}</div>
                @enderror
            </div>
        </div>

        <div class="form-group mt-5 col-lg-12 ">
            <div class="float-left ">
                <a class="btn btn-outline-primary" href="{{ route('admin.companies.index') }}" title="Go back"> <i class="fas fa-backward "></i> </a>
            </div>
            <div class="col-xs-offset-2 col-xs-8 float-right">
                <button type="submit" class="btn btn-outline-primary">Створити</button>
            </div>
        </div>
    </form>
</div>

@endsection

@push('content-css')
    <link href="https://cdn.jsdelivr.net/npm/select2@4.1.0-rc.0/dist/css/select2.min.css" rel="stylesheet" />
    <style>
        .select2-container--default .select2-selection--multiple .select2-selection__choice {
            background-color: #3c8dbc;
            border-color: #367fa9;
            color: #fff;
        }
        .select2-container--default .select2-selection--multiple .select2-selection__choice__remove {
            margin-right: 5px;
            color: rgba(255,255,255,0.7);
            border-right: none;
        }
    </style>
@endpush

@push('content-js')
    <script src="https://cdn.jsdelivr.net/npm/select2@4.1.0-rc.0/dist/js/select2.min.js"></script>
    <script>
        $(function () {
            //Initialize Select2 Elements
            $(".select2").select2();
        });
    </script>
@endpush

resources/views/admin/pages/clients/edit.blade.php
@extends('admin.layouts.app')
@section('content-page', 'Редагувати дані клієнта')
@section('content-title', 'Редагувати дані клієнта')
@section('content')

    <div class="container-fluid col-lg-8 mt-2">
        <form method="POST" action="{{ route('admin.clients.update', $client) }}">
            @csrf
            @method('PUT')
            <div class="form-group col-lg-12 mb-2">
                <label for="inputName" class="col-xs-2 control-label">Ім'я:</label>
                <div class="col-xs-8">
                    <input type="text" name="name" class="form-control" id="inputName" placeholder="Введіть ім'я"  value="{{old('name',$client->name)}}">
                    <input type="hidden" name="id" class="form-control"  value="{{ $client->id }}">
                    @error('name')
                    <div class="alert alert-danger">{{ $message }}</div>
                    @enderror
                </div>
            </div>
            <div class="form-group col-lg-12 mb-2">
                <label for="inputSurName" class="col-xs-2 control-label">Прізвище:</label>
                <div class="col-xs-8">
                    <input type="text" name="surname" class="form-control" id="inputSurName" placeholder="Введіть прізвище"  value="{{old('surname',$client->surname)}}">
                    @error('surname')
                    <div class="alert alert-danger">{{ $message }}</div>
                    @enderror
                </div>
            </div>
            <div class="form-group col-lg-12 mb-2">
                <label for="inputEmail" class="col-xs-2 control-label">Електрона адреса:</label>
                <div class="col-xs-8">
                    <input type="text" name="email" class="form-control" id="inputEmail" placeholder="Введіть електронну адресу" value="{{old('email',$client->email)}}">
                    @error('email')
                    <div class="alert alert-danger">{{ $message }}</div>
                    @enderror
                </div>
            </div>
            <div class="form-group col-lg-12 mb-2">
                <label for="inputCompanies" class="col-xs-2 control-label">Компанії клієнта:</label>
                <div class="col-xs-8">
                    <select name="companies[]" data-companies="{{ $client->companies->pluck('id') }}" class="form-control select2" multiple="multiple" id="inputCompanies"
                            data-placeholder="Виберіть компанію закріплену за клієнтом"
                    >
                        @foreach($companies as $id => $name)
                            <option value="{{ $id }}">{{ $name }}</option>
                        @endforeach
                    </select>
                    @error('companies')
                    <div class="alert alert-danger">{{ $message }}</div>
                    @enderror
                </div>
            </div>

            <div class="form-group mt-5 col-lg-12 ">
                <div class="float-left ">
                    <a class="btn btn-outline-primary" href="{{ route('admin.clients.index') }}" title="Go back"> <i class="fas fa-backward "></i> </a>
                </div>
                <div class="col-xs-offset-2 col-xs-8 float-right">
                    <button type="submit" class="btn btn-outline-primary">Зберегти</button>
                </div>
            </div>
        </form>
    </div>

@endsection

@push('content-css')
    <link href="https://cdn.jsdelivr.net/npm/select2@4.1.0-rc.0/dist/css/select2.min.css" rel="stylesheet" />
    <style>
        .select2-container--default .select2-selection--multiple .select2-selection__choice {
            background-color: #3c8dbc;
            border-color: #367fa9;
            color: #fff;
        }
        .select2-container--default .select2-selection--multiple .select2-selection__choice__remove {
            margin-right: 5px;
            color: rgba(255,255,255,0.7);
            border-right: none;
        }
    </style>
@endpush

@push('content-js')
    <script src="https://cdn.jsdelivr.net/npm/select2@4.1.0-rc.0/dist/js/select2.min.js"></script>
    <script>
        $(function () {
            //Initialize Select2 Elements
            $(".select2").select2();
            let companies = $("#inputCompanies");
            companies.val(companies.data('companies')).trigger('change');
        });
    </script>
@endpush

resources/views/admin/pages/clients/index.blade.php
@extends('admin.layouts.app')

@section('content-page', 'Клієнти')
@section('content-title', 'Клієнти')
@section('content')
    <div class="container-fluid">
        <div class="pull-right">
            <a class="btn btn-outline-primary" href="{{ route('admin.clients.create') }}" title="Create a client"> <i class="fas fa-plus-circle "></i>
                Додати клієнта</a>
        </div>
        <div class="card-alert m-3">
            <div class="card card-primary">
                @if ($message = Session::get('success'))
                    <div class="alert alert-success">
                        <p>{{ $message }}</p>
                    </div>
                @endif
            </div>
        </div>
        <div class="container-fluid">
            <div class="row">
                <div class="col-sm-12">
                    <table id="clients" class="table table-bordered table-condensed table-striped">
                        <thead>
                        <tr>
                            <th>Ім'я</th>
                            <th>Прізвище</th>
                            <th>Електрона адреса</th>
                            <th class="w-10"></th>
                        </tr>
                        </thead>
                    </table>
                </div>
            </div>
        </div>
    </div>

@push('content-js')
    <script src="{{ asset('js/content/clients/index.js') }}" defer></script>
@endpush

@endsection

resources/views/admin/pages/clients/show.blade.php
@extends('admin.layouts.app')
@section('content-page', 'Дані про клієнта')
@section('content-title')
    Дані про компанію {{ $client->name }}
@endsection

@section('content')
    <div class="container mt-2">
        <div class="row">
            <div class="col-xs-12 col-sm-12 col-md-12">
                <div class="form-group">
                    <strong>Ім'я:</strong>
                    {{ $client->name }}
                </div>
            </div>
            <div class="col-xs-12 col-sm-12 col-md-12">
                <div class="form-group">
                    <strong>Прізвище:</strong>
                    {{ $client->surname }}
                </div>
            </div>
            <div class="col-xs-12 col-sm-12 col-md-12">
                <div class="form-group">
                    <strong>Електрона адреса:</strong>
                    {{ $client->email }}
                </div>
            </div>
            <div class="col-xs-12 col-sm-12 col-md-12">
                <div class="form-group">
                    <strong class="mr-3">Компанії клієнта:</strong>
                    @foreach($client->companies as $company)
                        <a class="mr-2"  href="{{ route('admin.companies.show', $company) }}" ><i class="fas fa-building text-info"></i>
                            {{$company->name}}
                        </a>
                    @endforeach
                </div>
            </div>

            <div class="col-xs-8 col-sm-8 col-md-8 mt-4">

                <div class="float-left mr-5">
                    <a class="btn btn-outline-primary" href="{{ route('admin.clients.index') }}" title="Go back"> <i class="fas fa-backward "></i> </a>
                </div>
                <div class="ml-5">
                    <a type="button" class="btn btn-outline-primary" href="{{ route('admin.clients.edit', $client) }}">Редагувати</a>
                </div>
            </div>
        </div>
    </div>
@endsection