routes/web.php
<?php

use App\Http\Controllers\Admin\AdminController;
use App\Http\Controllers\Admin\ClientController;
use App\Http\Controllers\Admin\CompanyController;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Auth::routes(['register' => false,'reset' => false,'confirm' => false,'verify' => false]);
Route::middleware(['auth'])->group(function () {
    Route::get('/',[AdminController::class ,'index'])->name('home');
    Route::name('admin.')->prefix('admin')->group(function (){
        Route::resource('/companies', CompanyController::class)->names('companies');
        Route::resource('/clients', ClientController::class)->names('clients');
    });
});

app/Models/Company.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Company extends Model
{
    use HasFactory;

    const ROUTE_KEY = 'admin.companies';
    /**
     * The attributes that are mass assignable.
     *
     * @var string[]
     */
    protected $fillable = [
        'name',
        'email',
        'foundation_year',
        'description',
    ];

    /**
     * Relationship with clients
     *
     * @return \Illuminate\Database\Eloquent\Relations\HasMany
     */
    public function clients()
    {
        return $this->belongsToMany(Client::class);
    }

    /**
     * Set the companies foundation_year.
     *
     * @param $data
     * @return void
     */
    public function setFoundationYearAttribute($data)
    {
        $this->attributes['foundation_year'] = $data ? $data->format('Y') : null ;
    }
}

app/Http/Controllers/Admin/CompanyController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use App\Http\Requests\CompamyUpdateRequest;
use App\Http\Requests\CompanyStoreRequest;
use App\Models\Company;
use App\Services\CompanyService;
use Illuminate\Contracts\Foundation\Application;
use Illuminate\Contracts\View\Factory;
use Illuminate\Contracts\View\View;
use Illuminate\Http\RedirectResponse;
use Illuminate\Http\Request;
use Illuminate\Http\Response;

class CompanyController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return Application|Factory|View
     */
    public function index(Request $request, CompanyService $companyService)
    {
        if ($request->ajax()) {
           return $companyService->getCompaniesDatatable();
        }
        return view('admin.pages.companies.index');
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return Application|Factory|View
     */
    public function create()
    {
        return view('admin.pages.companies.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param CompanyStoreRequest $request
     * @return \Illuminate\Http\RedirectResponse
     */
    public function store(CompanyStoreRequest $request, CompanyService $companyService)
    {
        $companyService->create($request->validated());
        return redirect()->route('admin.companies.index')->with('success','Компанію успішно створено');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return Application|Factory|View
     */
    public function show(Company $company)
    {
        return view('admin.pages.companies.show',compact('company'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param Company $company
     * @return Application|Factory|View
     */
    public function edit(Company $company)
    {
        return view('admin.pages.companies.edit',compact('company'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param CompamyUpdateRequest $request
     * @param Company $company
     * @return \Illuminate\Http\RedirectResponse
     */
    public function update(CompamyUpdateRequest $request, Company $company)
    {
        $company->update($request->validated());
        return redirect()->route('admin.companies.index')->with('success','Компанію успішно оновлено');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param Company $company
     * @return RedirectResponse
     */
    public function destroy(Company $company)
    {
        $company->delete();
        return redirect()->route('admin.companies.index')->with('success','Компанію успішно видалено');
    }
}

resources/views/admin/pages/companies/create.blade.php
@extends('admin.layouts.app')
@section('content-page', 'Додати компанію')
@section('content-title', 'Додати компанію')
@section('content')

<div class="container-fluid col-lg-8 mt-2">
    <form method="POST" action="{{ route('admin.companies.store') }}">
        @csrf
        <div class="form-group col-lg-12 mb-2">
            <label for="inputName" class="col-xs-2 control-label">Назва компанії:</label>
            <div class="col-xs-8">
                <input type="text" name="name" class="form-control" id="inputName" placeholder="Введіть назву компаніїї"  value="{{old('name')}}">
                @error('name')
                <div class="alert alert-danger">{{ $message }}</div>
                @enderror
            </div>
        </div>
        <div class="form-group col-lg-12 mb-2">
            <label for="inputEmail" class="col-xs-2 control-label">Електрона адреса компанії:</label>
            <div class="col-xs-8">
                <input type="text" name="email" class="form-control" id="inputEmail" placeholder="Введіть електронну адреса компанії" value="{{old('email')}}">
                @error('email')
                <div class="alert alert-danger">{{ $message }}</div>
                @enderror
            </div>
        </div>
        <div class="form-group col-lg-12 mb-2">
            <label for="inputFoundationYear" class="col-xs-2 control-label">Рік заснування компанії:</label>
            <div class="col-xs-8">
                <input type="number" name="foundation_year" min="1901" max="2099" step="1"  class="form-control" id="inputFoundationYear" placeholder="Введіть рік заснування компанії" value="{{old('foundation_year')}}">
                @error('foundation_year')
                <div class="alert alert-danger">{{ $message }}</div>
                @enderror
            </div>
        </div>
        <div class="form-group col-lg-12 mb-2">
            <label for="inputDescription" class="col-xs-2 control-label">Опис компанії:</label>
            <div class="col-xs-8">
                <textarea  name="description" maxlength="250" class="form-control" id="inputDescription" placeholder="Введіть опис компанії">{{ old('description') }}</textarea>
                @error('description')
                <div class="alert alert-danger">{{ $message }}</div>
                @enderror
            </div>
        </div>
        <div class="form-group mt-5 col-lg-12 ">
            <div class="float-left ">
                <a class="btn btn-outline-primary" href="{{ route('admin.companies.index') }}" title="Go back"> <i class="fas fa-backward "></i> </a>
            </div>
            <div class="col-xs-offset-2 col-xs-8 float-right">
                <button type="submit" class="btn btn-outline-primary">Створити</button>
            </div>
        </div>
    </form>
</div>

@endsection

resources/views/admin/pages/companies/edit.blade.php
@extends('admin.layouts.app')
@section('content-page', 'Редагувати компанію')
@section('content-title', 'Редагувати компанію')
@section('content')

    <div class="container-fluid col-lg-8 mt-2">
        <form method="POST" action="{{ route('admin.companies.update', $company) }}">
            @csrf
            @method('PUT')
            <div class="form-group col-lg-12 mb-2">
                <label for="inputName" class="col-xs-2 control-label">Назва компанії:</label>
                <div class="col-xs-8">
                    <input type="text" name="name" class="form-control" id="inputName" placeholder="Введіть назву компаніїї"  value="{{old('name',$company->name)}}">
                    <input type="hidden" name="id" class="form-control"  value="{{ $company->id }}">
                    @error('name')
                    <div class="alert alert-danger">{{ $message }}</div>
                    @enderror
                </div>
            </div>
            <div class="form-group col-lg-12 mb-2">
                <label for="inputEmail" class="col-xs-2 control-label">Електрона адреса компанії:</label>
                <div class="col-xs-8">
                    <input type="text" name="email" class="form-control" id="inputEmail" placeholder="Введіть електронну адреса компанії" value="{{old('email',$company->email)}}">
                    @error('email')
                    <div class="alert alert-danger">{{ $message }}</div>
                    @enderror
                </div>
            </div>
            <div class="form-group col-lg-12 mb-2">
                <label for="inputFoundationYear" class="col-xs-2 control-label">Рік заснування компанії:</label>
                <div class="col-xs-8">
                    <input type="number" name="foundation_year" min="1901" max="2099" step="1"  class="form-control" id="inputFoundationYear" placeholder="Введіть рік заснування компанії" value="{{old('foundation_year',$company->foundation_year)}}">
                    @error('foundation_year')
                    <div class="alert alert-danger">{{ $message }}</div>
                    @enderror
                </div>
            </div>
            <div class="form-group col-lg-12 mb-2">
                <label for="inputDescription" class="col-xs-2 control-label">Опис компанії:</label>
                <div class="col-xs-8">
                    <textarea  name="description" maxlength="250" class="form-control" id="inputDescription" placeholder="Введіть опис компанії">{{ old('description',$company->description) }}</textarea>
                    @error('description')
                    <div class="alert alert-danger">{{ $message }}</div>
                    @enderror
                </div>
            </div>
            <div class="form-group mt-5 col-lg-12 ">
                <div class="float-left ">
                    <a class="btn btn-outline-primary" href="{{ route('admin.companies.index') }}" title="Go back"> <i class="fas fa-backward "></i> </a>
                </div>
                <div class="col-xs-offset-2 col-xs-8 float-right">
                    <button type="submit" class="btn btn-outline-primary">Зберегти</button>
                </div>
            </div>
        </form>
    </div>

@endsection

resources/views/admin/pages/companies/index.blade.php
@extends('admin.layouts.app')

@section('content-page', 'Компанії')
@section('content-title', 'Компанії')
@section('content')
    <div class="container-fluid">
        <div class="pull-right">
            <a class="btn btn-outline-primary" href="{{ route('admin.companies.create') }}" title="Create a product"> <i class="fas fa-plus-circle "></i>
            Додати компанію</a>
        </div>

        <div class="card-alert m-3">
            <div class="card card-primary">
                @if ($message = Session::get('success'))
                    <div class="alert alert-success">
                        <p>{{ $message }}</p>
                    </div>
                @endif
            </div>
        </div>

        <div class="container-fluid">
            <div class="row">
                <div class="col-sm-12">
                    <table id="companies" class="table table-bordered table-condensed table-striped">
                        <thead>
                        <tr>
                            <th>Назва компанії</th>
                            <th>Електрона адреса компанії</th>
                            <th>Рік заснування компанії</th>
                            <th>Опис компанії</th>
                            <th class="w-10"></th>
                        </tr>
                        </thead>
                    </table>
                </div>
            </div>
        </div>
    </div>

@push('content-js')
    <script src="{{ asset('js/content/company/index.js') }}" defer></script>
@endpush

@endsection

resources/views/admin/pages/companies/show.blade.php
@extends('admin.layouts.app')
@section('content-page', 'Дані про компанію')
@section('content-title')
    Дані про компанію {{ $company->name }}
@endsection

@section('content')
    <div class="container mt-2">
        <div class="row">
            <div class="col-xs-12 col-sm-12 col-md-12">
                <div class="form-group">
                    <strong>Назва компанії:</strong>
                    {{ $company->name }}
                </div>
            </div>
            <div class="col-xs-12 col-sm-12 col-md-12">
                <div class="form-group">
                    <strong>Електрона адреса компанії:</strong>
                    {{ $company->email }}
                </div>
            </div>
            <div class="col-xs-12 col-sm-12 col-md-12">
                <div class="form-group">
                    <strong>Рік заснування компанії:</strong>
                    {{ $company->foundation_year }}
                </div>
            </div>
            <div class="col-xs-12 col-sm-12 col-md-12">
                <div class="form-group">
                    <strong>Опис компанії:</strong>
                    {{ $company->description }}
                </div>
            </div>

            <div class="col-xs-8 col-sm-8 col-md-8 mt-4">

                <div class="float-left mr-5">
                    <a class="btn btn-outline-primary" href="{{ route('admin.companies.index') }}" title="Go back"> <i class="fas fa-backward "></i> </a>
                </div>
                <div class="ml-5">
                    <a type="button" class="btn btn-outline-primary" href="{{ route('admin.companies.edit', $company->id) }}">Редагувати</a>
                </div>
            </div>
        </div>
    </div>
@endsection